version: 0.0
os: linux
files:
  - source: /
    destination: /opt/feedback-bot
#permissions:
#  - object: /opt/feedback-bot
#    type:
#      - directory
#      - file
hooks:
  AfterInstall:
    - location: install_requirements.sh
      timeout: 300
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
#  ApplicationStop:
#    - location: stop_server.sh
#      timeout: 300
